main = ".open-next/worker.js"
name = "insight-out"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "c65ee9811c5f4a00b39e7415c187d33b"
